# Generated by Django 5.1.5 on 2025-12-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('announcement', models.TextField(blank=True, verbose_name='Анонс')),
                ('red_flags', models.TextField(blank=True, verbose_name='Красные флаги')),
                ('players_min', models.PositiveIntegerField(default=1, verbose_name='Минимум игроков')),
                ('players_max', models.PositiveIntegerField(default=10, verbose_name='Максимум игроков')),
                ('female_roles_min', models.PositiveIntegerField(default=0, verbose_name='Минимум женских ролей')),
                ('female_roles_max', models.PositiveIntegerField(default=0, verbose_name='Максимум женских ролей')),
                ('male_roles_min', models.PositiveIntegerField(default=0, verbose_name='Минимум мужских ролей')),
                ('male_roles_max', models.PositiveIntegerField(default=0, verbose_name='Максимум мужских ролей')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['-created_at'],
            },
        ),
    ]
