# Generated by Django 5.1.5 on 2025-12-24 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время прогона')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='server.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Прогон',
                'verbose_name_plural': 'Прогоны',
                'ordering': ['date'],
            },
        ),
    ]
