# Generated by Django 5.1.5 on 2025-12-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_add_convention_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='games/posters/', verbose_name='Постер'),
        ),
    ]
