# Generated by Django 5.1.5 on 2025-12-24 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_add_convention_event_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='conventionevent',
            name='runs',
            field=models.ManyToManyField(blank=True, related_name='convention_events', to='server.run', verbose_name='Прогоны'),
        ),
        migrations.AlterField(
            model_name='run',
            name='convention_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_runs', to='server.conventionevent', verbose_name='Проведение конвента'),
        ),
    ]
