# Generated by Django 5.1.5 on 2025-12-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_conventionevent_runs_alter_run_convention_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conventionevent',
            name='games',
        ),
    ]
