# Generated by Django 5.1.5 on 2025-12-28 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_add_run_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConventionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('link_type', models.CharField(choices=[('vk', 'ВКонтакте'), ('telegram', 'Telegram'), ('website', 'Сайт'), ('discord', 'Discord'), ('youtube', 'YouTube'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип ссылки')),
                ('title', models.CharField(blank=True, help_text='Опциональное название ссылки (если не указано, используется тип)', max_length=100, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('convention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='server.convention', verbose_name='Конвент')),
            ],
            options={
                'verbose_name': 'Ссылка конвента',
                'verbose_name_plural': 'Ссылки конвентов',
                'ordering': ['link_type', 'title'],
            },
        ),
    ]
