# Generated by Django 5.1.5 on 2025-12-29

import django.db.models.deletion
from django.db import migrations, models


def migrate_regions_forward(apps, schema_editor):
    """Создаёт регионы из существующих текстовых значений и связывает города"""
    City = apps.get_model('server', 'City')
    Region = apps.get_model('server', 'Region')
    
    # Получаем уникальные непустые названия регионов
    region_names = City.objects.exclude(
        old_region__isnull=True
    ).exclude(
        old_region=''
    ).values_list('old_region', flat=True).distinct()
    
    # Создаём регионы
    regions_map = {}
    for name in region_names:
        region, created = Region.objects.get_or_create(name=name)
        regions_map[name] = region
    
    # Обновляем города со ссылками на регионы
    for city in City.objects.exclude(old_region__isnull=True).exclude(old_region=''):
        city.region = regions_map.get(city.old_region)
        city.save()


def migrate_regions_backward(apps, schema_editor):
    """Восстанавливает текстовые значения регионов из связей"""
    City = apps.get_model('server', 'City')
    
    for city in City.objects.filter(region__isnull=False):
        city.old_region = city.region.name
        city.save()


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_add_convention_link_model'),
    ]

    operations = [
        # 1. Создаём модель Region
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['name'],
            },
        ),
        # 2. Переименовываем старое текстовое поле region в old_region
        migrations.RenameField(
            model_name='city',
            old_name='region',
            new_name='old_region',
        ),
        # 3. Добавляем новое ForeignKey поле region
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='cities',
                to='server.region',
                verbose_name='Регион'
            ),
        ),
        # 4. Мигрируем данные
        migrations.RunPython(migrate_regions_forward, migrate_regions_backward),
        # 5. Удаляем старое текстовое поле
        migrations.RemoveField(
            model_name='city',
            name='old_region',
        ),
    ]

