# Generated by Django 5.1.5 on 2025-12-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_add_region_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='technicians',
            field=models.PositiveIntegerField(default=0, verbose_name='Игротехники'),
        ),
    ]
