# Generated by Django 5.1.5 on 2025-12-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_add_game_technicians'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='timezone',
            field=models.CharField(
                choices=[
                    ('Europe/Kaliningrad', 'Калининград (UTC+2)'),
                    ('Europe/Moscow', 'Москва (UTC+3)'),
                    ('Europe/Samara', 'Самара (UTC+4)'),
                    ('Asia/Yekaterinburg', 'Екатеринбург (UTC+5)'),
                    ('Asia/Omsk', 'Омск (UTC+6)'),
                    ('Asia/Krasnoyarsk', 'Красноярск (UTC+7)'),
                    ('Asia/Irkutsk', 'Иркутск (UTC+8)'),
                    ('Asia/Yakutsk', 'Якутск (UTC+9)'),
                    ('Asia/Vladivostok', 'Владивосток (UTC+10)'),
                    ('Asia/Magadan', 'Магадан (UTC+11)'),
                    ('Asia/Kamchatka', 'Камчатка (UTC+12)'),
                ],
                default='Europe/Moscow',
                max_length=50,
                verbose_name='Часовой пояс'
            ),
        ),
    ]
