# Generated by Django 5.1.5 on 2026-01-01 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_add_city_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conventionevent',
            name='runs',
        ),
    ]
