# Generated by Django 5.1.5 on 2026-01-01 07:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_remove_conventionevent_runs_m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convention',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='game',
            name='master',
        ),
        migrations.RemoveField(
            model_name='run',
            name='master',
        ),
        migrations.AddField(
            model_name='convention',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='organized_conventions', to=settings.AUTH_USER_MODEL, verbose_name='Организаторы'),
        ),
        migrations.AddField(
            model_name='conventionevent',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='organized_convention_events', to=settings.AUTH_USER_MODEL, verbose_name='Организаторы'),
        ),
        migrations.AddField(
            model_name='game',
            name='creators',
            field=models.ManyToManyField(blank=True, related_name='games', to=settings.AUTH_USER_MODEL, verbose_name='Создатели'),
        ),
        migrations.AddField(
            model_name='run',
            name='masters',
            field=models.ManyToManyField(blank=True, related_name='runs', to=settings.AUTH_USER_MODEL, verbose_name='Мастера'),
        ),
    ]
