# Generated by Django 5.1.5 on 2026-01-01 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_remove_convention_organizer_remove_game_master_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='duration',
            field=models.PositiveIntegerField(default=180, help_text='Продолжительность прогона в минутах', verbose_name='Продолжительность (минут)'),
        ),
        migrations.AddField(
            model_name='run',
            name='max_players',
            field=models.PositiveIntegerField(blank=True, help_text='Если не указано, берётся из игры', null=True, verbose_name='Максимум игроков'),
        ),
        migrations.AddField(
            model_name='run',
            name='registration_open',
            field=models.BooleanField(default=True, verbose_name='Регистрация открыта'),
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вместимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venues', to='server.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Площадка',
                'verbose_name_plural': 'Площадки',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='run',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='server.venue', verbose_name='Площадка'),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_preference', models.CharField(choices=[('any', 'Любая'), ('female', 'Женская'), ('male', 'Мужская')], default='any', max_length=10, verbose_name='Предпочтение по роли')),
                ('is_technician', models.BooleanField(default=False, verbose_name='Игротехник')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('cancelled', 'Отменена'), ('waitlist', 'В листе ожидания')], default='confirmed', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, help_text='Дополнительная информация от игрока', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='server.run', verbose_name='Прогон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрации',
                'ordering': ['created_at'],
                'unique_together': {('run', 'user')},
            },
        ),
    ]
