# Generated by Django 5.1.5 on 2026-01-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_add_room_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='venue',
        ),
        migrations.AddField(
            model_name='run',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='runs', to='server.room', verbose_name='Помещения'),
        ),
    ]
