# Generated by Django 5.1.5 on 2026-01-09 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_run_replace_venue_with_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='conventionevent',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convention_events', to='server.venue', verbose_name='Площадка'),
        ),
    ]
