# Generated by Django 5.1.5 on 2026-01-10 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_add_venue_to_convention_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('date', models.DateTimeField(verbose_name='Дата и время начала')),
                ('duration', models.PositiveIntegerField(default=60, help_text='Продолжительность события в минутах', verbose_name='Продолжительность (минут)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('convention_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_events', to='server.conventionevent', verbose_name='Проведение конвента')),
            ],
            options={
                'verbose_name': 'Общее событие',
                'verbose_name_plural': 'Общие события',
                'ordering': ['date'],
            },
        ),
    ]
