# Generated by Django 5.1.5 on 2026-01-10 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0021_add_common_event_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conventionevent',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Максимальное количество участников (если не указано — без ограничений)', null=True, verbose_name='Лимит участников'),
        ),
        migrations.AddField(
            model_name='conventionevent',
            name='registration_open',
            field=models.BooleanField(default=False, verbose_name='Регистрация открыта'),
        ),
        migrations.CreateModel(
            name='ConventionEventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, help_text='Дополнительная информация от участника', verbose_name='Комментарий')),
                ('admin_comment', models.TextField(blank=True, help_text='Заметка организатора (не видна участнику)', verbose_name='Комментарий организатора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('convention_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='server.conventionevent', verbose_name='Проведение конвента')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convention_event_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Регистрация на конвент',
                'verbose_name_plural': 'Регистрации на конвент',
                'ordering': ['created_at'],
                'unique_together': {('convention_event', 'user')},
            },
        ),
    ]
