# Generated by Django 5.1.5 on 2026-01-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0022_add_convention_event_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('cancelled', 'Отменена'), ('waitlist', 'В листе ожидания')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
